---
# Handlers for ansible-role-forgejo

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart forgejo service
  ansible.builtin.systemd:
    name: forgejo
    state: restarted
  when: forgejo_service_enabled | default(true)

- name: Restart forgejo-runner service
  ansible.builtin.systemd:
    name: forgejo-runner
    state: restarted
  when:
    - forgejo_runner_enabled | default(false)
    - forgejo_runner_service_enabled | default(true)
