---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: rockylinux:9
    pre_build_image: false
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
provisioner:
  name: ansible
  playbooks:
    converge: converge-runner.yml
    verify: verify-runner.yml
verifier:
  name: ansible
scenario:
  name: runner
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy