---
name: CI
'on':
  pull_request:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v4

      - name: Run ansible-lint
        run: |
          mise run lint
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  # molecule:
  #   name: Molecule
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   strategy:
  #     matrix:
  #       distro:
  #         - rockylinux9

  #   steps:
  #     - name: Check out the codebase
  #       uses: actions/checkout@v4

  #     - name: Install mise
  #       uses: jdx/mise-action@v4

  #     - name: Run Molecule tests
  #       run: |
  #         mise run molecule-test
  #       env:
  #         PY_COLORS: '1'
  #         ANSIBLE_FORCE_COLOR: '1'
  #         MOLECULE_DISTRO: ${{ matrix.distro }}
