---
name: CI
'on':
  pull_request:
  push:
  schedule:
    - cron: "0 2 * * 0"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Run ansible-lint
        run: |
          devbox run -- ansible-lint .
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        distro:
          - rockylinux9

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Run Molecule tests
        run: |
          devbox run -- molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
