---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: Release
'on':
  push:
    tags:
      - '*'

permissions:
  contents: write

defaults:
  run:
    working-directory: 'sgaunet.forgejo'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Run ansible-lint
        run: |
          devbox run -- ansible-lint .
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Run Molecule tests (Rocky Linux)
        run: |
          devbox run -- molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: rockylinux9

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'sgaunet.forgejo'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}  $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)

  gh-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            README.md
            LICENSE
